### ISSUE TITLE
Некорректная работа программы

### ISSUE THREAD

**Issue by GrigsyChudin** [AtariOverlord09/gowebcalc#1]
`/api/v1/calculate` - правильный url endpoint`a

В твоём случае, `/api/v1/calculate/` - обрати на это внимание!
![image](https://github.com/user-attachments/assets/6aff46f3-8da1-4adc-b698-27299651713c)
Видишь запрос POST, почему в консоли GET?
![image](https://github.com/user-attachments/assets/e11d7e89-f1de-4d71-859c-0513d7d2576b)

Сервис не работает корректно при больших значениях
![image](https://github.com/user-attachments/assets/a71ef459-c013-438b-9524-a3317bfcc314)

**Comment by AtariOverlord09** [comment]
1. POST запросы принято закрывать чертой, а в GET нет. Условие задачи не учитывает этого.
2. Это какой-то баг, ведь по коду ты можешь глянуть что middleware просто печатает метод запроса.
3. Да, ведь это переполнение типа данных, судя по всему. Наверное, следует возвращать 500 или 400 при таком кейсе.
